### ISSUE TITLE
Error adding Java lambda layer

### ISSUE THREAD

**Issue by alexbujenita** [open-telemetry/opentelemetry-lambda-extension#852] opened 2023-08-17 13:30 UTC
**Describe the bug**
Trying to add `arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-x86_64-ver-1-28-0:1`

presents this error message

`Failed to load layer version details: User: arn:aws:sts::486979256902:assumed-role/developer/<USER> is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-x86_64-ver-1-28-0:1 because no resource-based policy allows the lambda:GetLayerVersion action`

**Steps to reproduce**
Add eu-west-1 lambda layer

**What did you expect to see?**
Confirmation of the added lambda layer

**What did you see instead?**
A permission error

**What version of collector/language SDK version did you use?**
Version: (e.g., `v0.58.0`, `v1.11.0`, etc)

**What language layer did you use?**
Java

**Additional context**
Can't try different region as we work in eu-west-1

**Comment by AndreasBoegh** [comment] 2023-09-28 09:19
This is not a bug, you need to grant `lambda:GetLayerVersion` on `arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-x86_64-ver-1-28-0:1` for your user `arn:aws:sts::486979256902:assumed-role/developer/<USER>`

**Comment by tylerbenson** [comment] 2023-12-14 17:34
@AndreasBoegh thanks for chiming in. I'm going to close this issue.

**Closed as completed by tylerbenson** 2023-12-14 17:34 UTC
Labels: bug
