### ISSUE TITLE
Passing configuration function to nodejs lambda instrumentation package

### ISSUE THREAD

**Issue by sgracias1** [open-telemetry/opentelemetry-lambda-extension#827] opened 2023-07-31 19:51 UTC
**Describe the bug**
The lambda instrumentation layer provides a way to pass a configuration function to @opentelemetry/instrumentation-aws-lambda ([link](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/packages/layer/src/wrapper.ts#L68)).  However it is not clear how the user would provide such a function. 
I have tried placing such a function definition at the root of my lambda function but that doesn't seem to work, the only place the definition was picked up was if the wrapper file itself was modified. 

**What did you expect to see?**
Allow user to pass the configuration function to the lambda instrumentation package
Is providing the configuration function by the user currently supported, if so how would a user provide this function

**What version of collector/language SDK version did you use?**
nodejs layer 0.2.0

**What language layer did you use?**
Nodejs

**Additional context**

**Comment by timothymathison** [comment] 2024-01-04 20:26
Is this a duplicate of #232 ?

**Comment by mzl-md** [comment] 2024-06-11 09:47
aws-otel-lambda uses these global functions: https://github.com/aws-observability/aws-otel-lambda/blob/main/nodejs/wrapper-adot/src/adot-extension.ts#L29
I think you have to create a custom downstream repo of opentelemetry-lambda and modify it similar to how aws-otel-lambda does it, see their [build.sh](https://github.com/aws-observability/aws-otel-lambda/blob/main/nodejs/build.sh).

**Comment by tylerbenson** [comment] 2024-06-11 22:57
I'm going to close this issue.  If it's not resolved, let me know and I can reopen it.

**Closed as completed by tylerbenson** 2024-06-11 22:57 UTC
Labels: bug
